const aiServices = [
  {
    id: "chatgpt",
    name: "ChatGPT",
    category: ["글쓰기", "코딩", "업무 생산성"],
    shortDescription: "대화형 AI를 통해 글쓰기, 요약, 코딩, 아이디어 정리에 활용할 수 있는 범용 AI 서비스입니다.",
    officialUrl: "https://chatgpt.com",
    pricingType: "부분 무료",
    planType: "Free / Plus / Team / Enterprise",
    monthlyPrice: 20,
    priceText: "월 $20부터",
    hasFreePlan: true,
    strengths: ["범용성이 높음", "한국어 지원이 좋음", "다양한 작업에 활용 가능"],
    weaknesses: ["고급 기능은 유료 플랜 중심", "일부 최신 정보는 확인이 필요할 수 있음"],
    recommendedUses: ["문서 작성", "코딩 보조", "요약", "아이디어 정리"],
    recommendedUsers: ["개인 사용자", "기획자", "개발자", "학생"],
    notes: "입문자에게도 추천하기 좋은 범용 AI 서비스입니다.",
    difficulty: "쉬움",
    koreanSupport: true,
    mobileAvailable: true,
    apiAvailable: true,
    teamFeatures: true,
    alternatives: ["Claude", "Gemini", "Perplexity"],
    tags: ["대화형 AI", "생산성", "글쓰기", "코딩"],
    updatedAt: "2026-10-07",
    rating: 4.8,
    beginnerFriendly: true
  },
  {
    id: "claude",
    name: "Claude",
    category: ["글쓰기", "문서 분석", "코딩"],
    shortDescription: "긴 문서 이해와 자연스러운 글쓰기, 분석 업무에 강한 대화형 AI 서비스입니다.",
    officialUrl: "https://claude.ai",
    pricingType: "부분 무료",
    planType: "Free / Pro / Team / Enterprise",
    monthlyPrice: 20,
    priceText: "월 $20부터",
    hasFreePlan: true,
    strengths: ["긴 문서 처리에 강함", "글의 톤 조절이 자연스러움", "분석형 작업에 적합"],
    weaknesses: ["일부 지역이나 기능은 제한될 수 있음", "이미지 생성 기능은 별도 도구가 필요"],
    recommendedUses: ["리서치 정리", "문서 요약", "기획서 초안", "코드 리뷰"],
    recommendedUsers: ["마케터", "기획자", "연구자", "개발자"],
    notes: "문서 기반 업무가 많은 사용자에게 잘 맞습니다.",
    difficulty: "쉬움",
    koreanSupport: true,
    mobileAvailable: true,
    apiAvailable: true,
    teamFeatures: true,
    alternatives: ["ChatGPT", "Gemini", "Perplexity"],
    tags: ["대화형 AI", "문서 분석", "리서치"],
    updatedAt: "2026-10-07",
    rating: 4.7,
    beginnerFriendly: true
  },
  {
    id: "gemini",
    name: "Gemini",
    category: ["검색", "업무 생산성", "글쓰기"],
    shortDescription: "Google 생태계와 연결해 검색, 문서 작성, 아이디어 정리에 활용하기 좋은 AI 서비스입니다.",
    officialUrl: "https://gemini.google.com",
    pricingType: "부분 무료",
    planType: "Free / Google AI Pro",
    monthlyPrice: 19.99,
    priceText: "월 $19.99부터",
    hasFreePlan: true,
    strengths: ["Google 서비스와 연동성이 좋음", "멀티모달 작업 지원", "검색 기반 답변에 유리"],
    weaknesses: ["워크스페이스 연동은 계정 환경에 따라 차이가 있음", "답변 검증은 필요"],
    recommendedUses: ["검색 보조", "이메일 초안", "문서 작성", "아이디어 발상"],
    recommendedUsers: ["Google Workspace 사용자", "학생", "직장인"],
    notes: "Google 도구를 자주 쓰는 사용자에게 편리합니다.",
    difficulty: "쉬움",
    koreanSupport: true,
    mobileAvailable: true,
    apiAvailable: true,
    teamFeatures: true,
    alternatives: ["ChatGPT", "Claude", "Perplexity"],
    tags: ["Google", "검색", "생산성"],
    updatedAt: "2026-10-07",
    rating: 4.5,
    beginnerFriendly: true
  },
  {
    id: "perplexity",
    name: "Perplexity",
    category: ["검색", "리서치"],
    shortDescription: "출처 기반 답변과 빠른 리서치에 특화된 AI 검색 서비스입니다.",
    officialUrl: "https://www.perplexity.ai",
    pricingType: "부분 무료",
    planType: "Free / Pro / Enterprise",
    monthlyPrice: 20,
    priceText: "월 $20부터",
    hasFreePlan: true,
    strengths: ["출처 확인이 편함", "리서치 속도가 빠름", "검색형 질문에 강함"],
    weaknesses: ["창작형 글쓰기는 전문 도구보다 약할 수 있음", "출처 품질 확인이 필요"],
    recommendedUses: ["시장 조사", "자료 조사", "뉴스 확인", "논점 정리"],
    recommendedUsers: ["기획자", "연구자", "마케터", "학생"],
    notes: "정보 탐색과 근거 확인 중심으로 쓰기 좋습니다.",
    difficulty: "쉬움",
    koreanSupport: true,
    mobileAvailable: true,
    apiAvailable: true,
    teamFeatures: true,
    alternatives: ["ChatGPT", "Gemini", "Consensus"],
    tags: ["AI 검색", "리서치", "출처"],
    updatedAt: "2026-10-07",
    rating: 4.6,
    beginnerFriendly: true
  },
  {
    id: "midjourney",
    name: "Midjourney",
    category: ["이미지 생성", "디자인"],
    shortDescription: "고품질 이미지 생성에 강한 AI 이미지 제작 서비스입니다.",
    officialUrl: "https://www.midjourney.com",
    pricingType: "유료",
    planType: "Basic / Standard / Pro / Mega",
    monthlyPrice: 10,
    priceText: "월 $10부터",
    hasFreePlan: false,
    strengths: ["이미지 퀄리티가 높음", "예술적 스타일 표현이 강함", "커뮤니티 예제가 풍부함"],
    weaknesses: ["무료 플랜이 없음", "프롬프트 작성에 익숙해질 시간이 필요"],
    recommendedUses: ["콘셉트 이미지", "브랜딩 시안", "광고 비주얼", "일러스트 제작"],
    recommendedUsers: ["디자이너", "마케터", "크리에이터"],
    notes: "시각 결과물의 분위기와 완성도를 중시할 때 적합합니다.",
    difficulty: "보통",
    koreanSupport: false,
    mobileAvailable: true,
    apiAvailable: false,
    teamFeatures: false,
    alternatives: ["DALL-E", "Leonardo AI", "Ideogram"],
    tags: ["이미지", "디자인", "크리에이티브"],
    updatedAt: "2026-10-07",
    rating: 4.7,
    beginnerFriendly: false
  },
  {
    id: "canva",
    name: "Canva",
    category: ["디자인", "시각화/PPT"],
    shortDescription: "템플릿과 AI 기능을 함께 제공하는 온라인 디자인 제작 도구입니다.",
    officialUrl: "https://www.canva.com",
    pricingType: "부분 무료",
    planType: "Free / Pro / Teams / Enterprise",
    monthlyPrice: 15,
    priceText: "월 $15부터",
    hasFreePlan: true,
    strengths: ["템플릿이 풍부함", "초보자도 사용하기 쉬움", "협업 기능이 편리함"],
    weaknesses: ["고급 디자인 제어는 전문 툴보다 제한적", "일부 소재와 기능은 유료"],
    recommendedUses: ["SNS 이미지", "프레젠테이션", "간단한 영상", "마케팅 자료"],
    recommendedUsers: ["마케터", "소상공인", "교육자", "팀 사용자"],
    notes: "빠르게 결과물을 만들어야 하는 비디자이너에게 특히 좋습니다.",
    difficulty: "쉬움",
    koreanSupport: true,
    mobileAvailable: true,
    apiAvailable: true,
    teamFeatures: true,
    alternatives: ["Adobe Express", "Gamma", "Microsoft Designer"],
    tags: ["디자인", "PPT", "템플릿"],
    updatedAt: "2026-10-07",
    rating: 4.6,
    beginnerFriendly: true
  },
  {
    id: "gamma",
    name: "Gamma",
    category: ["시각화/PPT", "업무 생산성"],
    shortDescription: "AI로 프레젠테이션, 문서, 웹페이지 초안을 빠르게 만드는 제작 도구입니다.",
    officialUrl: "https://gamma.app",
    pricingType: "부분 무료",
    planType: "Free / Plus / Pro",
    monthlyPrice: 10,
    priceText: "월 $10부터",
    hasFreePlan: true,
    strengths: ["초안 생성이 빠름", "슬라이드 구조화가 쉬움", "공유와 발표가 간편함"],
    weaknesses: ["세밀한 디자인 수정은 제한적일 수 있음", "브랜드 템플릿 작업은 확인 필요"],
    recommendedUses: ["제안서 초안", "교육 자료", "보고서", "랜딩 페이지 초안"],
    recommendedUsers: ["기획자", "강사", "스타트업", "마케터"],
    notes: "아이디어를 빠르게 발표 자료로 바꿀 때 유용합니다.",
    difficulty: "쉬움",
    koreanSupport: true,
    mobileAvailable: true,
    apiAvailable: false,
    teamFeatures: true,
    alternatives: ["Canva", "Beautiful.ai", "Tome"],
    tags: ["PPT", "문서", "발표"],
    updatedAt: "2026-10-07",
    rating: 4.4,
    beginnerFriendly: true
  },
  {
    id: "cursor",
    name: "Cursor",
    category: ["코딩", "개발"],
    shortDescription: "AI 코드 작성과 리팩터링을 지원하는 개발자용 코드 에디터입니다.",
    officialUrl: "https://www.cursor.com",
    pricingType: "부분 무료",
    planType: "Hobby / Pro / Business",
    monthlyPrice: 20,
    priceText: "월 $20부터",
    hasFreePlan: true,
    strengths: ["코드베이스 이해가 좋음", "개발 흐름 안에서 AI를 활용 가능", "리팩터링에 유용함"],
    weaknesses: ["개발 지식이 필요함", "대형 프로젝트에서는 비용과 보안 검토 필요"],
    recommendedUses: ["코드 작성", "버그 수정", "리팩터링", "코드 설명"],
    recommendedUsers: ["개발자", "개발 입문자", "기술 창업자"],
    notes: "AI 코딩 도구를 본격적으로 써보고 싶은 개발자에게 적합합니다.",
    difficulty: "보통",
    koreanSupport: true,
    mobileAvailable: false,
    apiAvailable: false,
    teamFeatures: true,
    alternatives: ["GitHub Copilot", "Windsurf", "Replit"],
    tags: ["코딩", "IDE", "개발"],
    updatedAt: "2026-10-07",
    rating: 4.7,
    beginnerFriendly: false
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    category: ["코딩", "개발"],
    shortDescription: "IDE 안에서 코드 자동완성, 설명, 테스트 작성을 돕는 AI 개발 도구입니다.",
    officialUrl: "https://github.com/features/copilot",
    pricingType: "유료",
    planType: "Individual / Business / Enterprise",
    monthlyPrice: 10,
    priceText: "월 $10부터",
    hasFreePlan: false,
    strengths: ["주요 IDE 지원", "코드 자동완성이 빠름", "팀/기업 관리 기능 제공"],
    weaknesses: ["무료 플랜은 제한적", "생성 코드 검토가 필요함"],
    recommendedUses: ["코드 자동완성", "테스트 작성", "반복 코드 작성", "코드 설명"],
    recommendedUsers: ["개발자", "개발팀", "기업 사용자"],
    notes: "기존 개발 환경에 자연스럽게 붙여 쓰기 좋습니다.",
    difficulty: "보통",
    koreanSupport: true,
    mobileAvailable: false,
    apiAvailable: false,
    teamFeatures: true,
    alternatives: ["Cursor", "Codeium", "Windsurf"],
    tags: ["코딩", "GitHub", "자동완성"],
    updatedAt: "2026-10-07",
    rating: 4.5,
    beginnerFriendly: false
  },
  {
    id: "notion-ai",
    name: "Notion AI",
    category: ["업무 생산성", "문서 작성"],
    shortDescription: "노션 문서 안에서 요약, 작성, 정리, 질의응답을 지원하는 AI 기능입니다.",
    officialUrl: "https://www.notion.com/product/ai",
    pricingType: "유료",
    planType: "AI Add-on / Business / Enterprise",
    monthlyPrice: 10,
    priceText: "월 $10부터",
    hasFreePlan: false,
    strengths: ["노션 워크스페이스와 결합이 좋음", "문서 정리에 편리함", "팀 지식 검색에 유용"],
    weaknesses: ["노션을 쓰지 않으면 활용도가 낮음", "고급 사용은 유료 중심"],
    recommendedUses: ["회의록 요약", "위키 정리", "문서 초안", "업무 지식 검색"],
    recommendedUsers: ["기획자", "운영팀", "스타트업", "프로젝트 매니저"],
    notes: "노션을 팀 지식베이스로 쓰는 조직에 특히 적합합니다.",
    difficulty: "쉬움",
    koreanSupport: true,
    mobileAvailable: true,
    apiAvailable: true,
    teamFeatures: true,
    alternatives: ["Coda AI", "ChatGPT", "Mem"],
    tags: ["노션", "문서", "생산성"],
    updatedAt: "2026-10-07",
    rating: 4.2,
    beginnerFriendly: true
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    category: ["음성 합성", "오디오"],
    shortDescription: "자연스러운 AI 음성 생성과 더빙, 보이스오버 제작에 특화된 서비스입니다.",
    officialUrl: "https://elevenlabs.io",
    pricingType: "부분 무료",
    planType: "Free / Starter / Creator / Pro / Scale",
    monthlyPrice: 5,
    priceText: "월 $5부터",
    hasFreePlan: true,
    strengths: ["음성 품질이 자연스러움", "다국어 더빙에 유용", "API 활용 가능"],
    weaknesses: ["상업적 이용 조건 확인 필요", "음성 클로닝은 윤리와 권한 검토 필요"],
    recommendedUses: ["내레이션", "더빙", "오디오북", "영상 보이스오버"],
    recommendedUsers: ["크리에이터", "교육자", "영상 제작자", "개발자"],
    notes: "음성 권리와 사용 범위를 반드시 확인하고 활용해야 합니다.",
    difficulty: "보통",
    koreanSupport: true,
    mobileAvailable: true,
    apiAvailable: true,
    teamFeatures: true,
    alternatives: ["PlayHT", "Murf", "Typecast"],
    tags: ["음성", "TTS", "더빙"],
    updatedAt: "2026-10-07",
    rating: 4.6,
    beginnerFriendly: true
  },
  {
    id: "runway",
    name: "Runway",
    category: ["영상 생성", "동영상 편집"],
    shortDescription: "AI 영상 생성, 편집, 배경 제거 등 크리에이티브 영상 작업을 지원하는 도구입니다.",
    officialUrl: "https://runwayml.com",
    pricingType: "부분 무료",
    planType: "Free / Standard / Pro / Unlimited / Enterprise",
    monthlyPrice: 15,
    priceText: "월 $15부터",
    hasFreePlan: true,
    strengths: ["영상 생성 기능이 강함", "편집 도구가 다양함", "크리에이티브 실험에 적합"],
    weaknesses: ["고품질 결과는 크레딧 비용이 들 수 있음", "결과 일관성 검토가 필요"],
    recommendedUses: ["AI 영상 생성", "광고 영상 시안", "배경 제거", "숏폼 제작"],
    recommendedUsers: ["영상 제작자", "마케터", "디자이너", "크리에이터"],
    notes: "영상 콘셉트 제작과 빠른 시안 검토에 좋습니다.",
    difficulty: "보통",
    koreanSupport: false,
    mobileAvailable: true,
    apiAvailable: true,
    teamFeatures: true,
    alternatives: ["Pika", "Luma", "Kling"],
    tags: ["영상", "편집", "생성형 AI"],
    updatedAt: "2026-10-07",
    rating: 4.5,
    beginnerFriendly: false
  },
  {
    id: "zapier",
    name: "Zapier",
    category: ["자동화", "업무 생산성"],
    shortDescription: "여러 앱을 연결해 반복 업무를 자동화하고 AI 기반 워크플로를 만들 수 있는 서비스입니다.",
    officialUrl: "https://zapier.com",
    pricingType: "부분 무료",
    planType: "Free / Professional / Team / Enterprise",
    monthlyPrice: 29.99,
    priceText: "월 $29.99부터",
    hasFreePlan: true,
    strengths: ["연동 앱이 많음", "반복 업무 자동화에 강함", "비개발자도 사용 가능"],
    weaknesses: ["복잡한 자동화는 설계가 필요함", "작업량이 늘면 비용이 증가"],
    recommendedUses: ["CRM 자동화", "알림 자동화", "데이터 전달", "AI 업무 흐름"],
    recommendedUsers: ["운영팀", "마케터", "영업팀", "1인 사업자"],
    notes: "반복 업무가 많은 팀의 생산성 개선에 적합합니다.",
    difficulty: "보통",
    koreanSupport: false,
    mobileAvailable: true,
    apiAvailable: true,
    teamFeatures: true,
    alternatives: ["Make", "n8n", "IFTTT"],
    tags: ["자동화", "워크플로", "연동"],
    updatedAt: "2026-10-07",
    rating: 4.3,
    beginnerFriendly: true
  },
  {
    id: "consensus",
    name: "Consensus",
    category: ["논문/학술", "리서치"],
    shortDescription: "학술 논문 기반으로 질문에 대한 근거와 요약을 제공하는 AI 리서치 도구입니다.",
    officialUrl: "https://consensus.app",
    pricingType: "부분 무료",
    planType: "Free / Premium / Teams",
    monthlyPrice: 11.99,
    priceText: "월 $11.99부터",
    hasFreePlan: true,
    strengths: ["논문 기반 근거 확인에 유리", "연구 질문 탐색이 빠름", "출처 추적이 쉬움"],
    weaknesses: ["학술 영역 외 질문에는 제한적", "원문 해석은 추가 검토 필요"],
    recommendedUses: ["논문 조사", "근거 확인", "연구 주제 탐색", "문헌 리뷰"],
    recommendedUsers: ["연구자", "학생", "의료/교육 분야 종사자"],
    notes: "학술 근거가 중요한 조사에서 보조 도구로 쓰기 좋습니다.",
    difficulty: "보통",
    koreanSupport: false,
    mobileAvailable: true,
    apiAvailable: false,
    teamFeatures: true,
    alternatives: ["Elicit", "Perplexity", "Google Scholar"],
    tags: ["논문", "학술", "리서치"],
    updatedAt: "2026-10-07",
    rating: 4.3,
    beginnerFriendly: true
  }
];
